---
# Ansible tasks
#
# OpenXPKI cron configuration

- name: Create directories for publishing
  file:
    state: 'directory'
    dest: '{{ item }}'
    owner: 'openxpki'
    group: 'www-data'
    mode: '2755'
  loop: '{{ openxpki_publishing_dirs }}'

- name: Regular CRL creation
  cron:
    name: 'Realm {{ item.name }} CRL publishing'
    job: >-
      /usr/bin/openxpkicmd --realm {{ item.name }} crl_issuance > /dev/null
    hour: '1'
    minute: '{{ 59 | random(seed=inventory_hostname + item.name) }}'
    user: root
    cron_file: 'openxpki'
  when: item.crl_publishing | default(false)
  loop: '{{ openxpki_realms }}'

...
